export const TOUR = [
  { tab: 'console', case: 'PT-8821', target: 'queue', title: 'Every contact becomes a case',
    text: 'Chats, voice notes and system alerts (a Soundbox going offline, a payout failing) land here as cases. Each row shows what the AI is doing, how confident it is, and how much time is left before a deadline.' },
  { tab: 'console', case: 'PT-8821', target: 'convo', title: 'The customer speaks their language',
    text: 'A kirana owner sends a Hindi voice note: yesterday\'s ₹14,200 has not reached his bank. The AI replies in Hindi and keeps him posted while it works. It also reminds him that Paytm never asks for PIN or OTP.' },
  { tab: 'console', case: 'PT-8821', target: 'timeline', title: 'Agent timeline: see every step',
    text: 'Each step shows what the AI did, which system it touched and how long it took. A fast decision model (Jev) classifies the case with a confidence score; plain code handles money and deadlines; the LLM plans and writes replies.',
    try: 'Click "Why?" under any step to see the reason behind it.' },
  { tab: 'console', case: 'PT-8821', target: 'approval', title: 'Sensitive actions wait for a human',
    text: 'Releasing a ₹14,200 hold is a sensitive action, so the AI stops and asks. The card says exactly what will happen, why, and the confidence. No vague "allow AI to continue".',
    try: 'Click "Approve ₹14,200 release" and watch the timeline continue.' },
  { tab: 'console', case: 'PT-8819', target: 'timeline', title: 'Small, safe fixes run on their own',
    text: 'Gupta Medical\'s Soundbox went silent and rent was still charged after a return. The AI pinged the device, sent a remote reboot, worked out ₹375 overcharged in code, and refunds it by itself because it is small, rule-eligible and high-confidence.',
    try: 'Watch the running step move to Done in a few seconds.' },
  { tab: 'console', case: 'PT-8830', target: 'timeline', title: 'Knowing when to hand over',
    text: 'A "digital arrest" scam report is P0. The AI time-stamps the report (it decides the customer\'s liability window), disables UPI on the device, shares 1930, and hands the case to the fraud desk in seconds with a full note.' },
  { tab: 'console', case: 'PT-8818', target: 'takeover', title: 'Humans stay in control',
    text: 'On any case an agent can pause the AI or take over. The AI never asks for PIN/OTP, never releases a police freeze, never rejects a complaint alone, and never approves credit.',
    try: 'Click "Take over" to move this case to yourself.' },
  { tab: 'console', case: 'PT-8821', target: 'c360', title: 'Full context, zero re-asks',
    text: 'The customer 360 and the timeline travel with the case. Whoever picks it up next never has to ask the customer to repeat themselves.' },
  { tab: 'chat', target: 'chat', title: 'What the merchant sees',
    text: 'A simple Hindi-first chat: voice in, live progress in plain words, a clear receipt, and big buttons like "Ho gaya", "Nahi hua" and "Insaan se baat".' },
  { tab: 'field', target: 'field', title: 'Field sales gets briefed',
    text: 'When a visit is needed, the AI books it on the field executive\'s route with a short brief: what went wrong, what was already done, and what to pitch.' },
  { tab: 'insights', target: 'kpis', title: 'What the ops head tracks',
    text: 'Resolution verified by backend action, first contact resolution, deadline breaches avoided, cost per case and CSAT. These are the outcomes the teammate is measured on.' },
  { tab: 'console', case: 'PT-8821', target: 'queue', title: 'Your turn',
    text: 'That is Sahayak: it decides, acts, verifies and knows when to call a human. Click around freely. You can restart this tour anytime from "Guided tour" in the sidebar.' },
]
